site_name: V-FOR-WaTer Documentation
site_url: https://vforwater.github.io/vforwater-documentation/
theme: 
    name: material
    palette:
        primary: 'black'
        accent: 'teal'
    logo: assets/V-FOR-WaTer favicon mittel.png
extra_css:
    - assets/css/extra.css

nav:
    - Home: index.md
    - About: about.md
    - User Guide:
        - Getting Started: user-guide/getting-started.md
        - Accessing Data: user-guide/accessing-data.md
        - Navigating through the Workspace: user-guide/workspace.md
        - Configuration: user-guide/configuration.md
        - Advanced Usage: user-guide/advanced-usage.md
    - Toolbox:
        - Toolbox Overview: toolbox/overview.md
    - Developers Guide:
        - Project Structure: user-guide/project-structure.md
        - Tools Architecture: user-guide/tools.md
        - How to add tools: user-guide/adding-tools.md
    - How to Cite: how-to-cite.md
    - Contact: contact.md