site_name: V-FOR-WaTer Documentation
site_url: https://vforwater.github.io/vforwater-documentation/
theme: 
    name: material
    palette:
        primary: 'black'
        accent: 'teal'
    logo: assets/V-FOR-WaTer favicon mittel.png
extra_css:
    - assets/css/extra.css

nav:
    - Home: index.md
    - About: about.md
    - User Guide:
        - Getting Started: user-guide/getting-started.md
        - Installation: user-guide/installation.md
        - Configuration: user-guide/configuration.md
        - Advanced Usage: user-guide/advanced-usage.md
